use_frameworks!

target 'CentrifugoiOS_Example', :exclusive => true do
  pod 'CentrifugoiOS', :path => '../'
end

target 'CentrifugoiOS_Tests', :exclusive => true do
  pod 'CentrifugoiOS', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            if target.name == 'CentrifugoiOS'
                target.build_settings(configuration.name)['ENABLE_TESTABILITY'] = 'YES'
            end
        end
    end
end
